### ISSUE TITLE
Code of Conduct for Ruby room

### ISSUE THREAD

**Issue by juliancheal** [fosdem-ruby/fosdem-ruby.github.io#11]
Hi,

It would be great, if the Ruby room at FOSDEM could have a Code of Conduct.
The Golang room will have one[1] as they mention, will probably be the same as Gophercon[2]
May I sugest the Ruby Conf [3] or Rails Conf[4] CoC (they're basically the same)

[1] https://twitter.com/francesc/status/660037057121796096
[2] http://gophercon.com/code-of-conduct/
[3] http://rubyconf.org/policies
[4] http://railsconf.com/policies

**Comment by toch** [comment]
Hi @juliancheal ,

very good point, in fact it's planned to use the one of the association Ruby Belgium https://github.com/brug-be/code_of_conduct. Any feedback on it is very welcome,

We'll mention it asap on the website.

**Comment by juliancheal** [comment]
:+1: That's great! Thanks @toch

**Comment by skade** [comment]
There is also the http://berlincodeofconduct.org/, maintained by your happy Ruby non-profit from Berlin and available in 5 languages.

**Comment by toch** [comment]
@skade i took inspiration from that one. I thought it was important that we had a commitment by having our "own". what do you think?

**Comment by skade** [comment]
@toch I'm split. Formulating an own statement can be a very binding thing and be important for the group feel :+1:. Downside is that details might be missed.

**Comment by toch** [comment]
@skade right I’ll double check. do you know who could review it?

**Comment by juliancheal** [comment]
Maybe @CoralineAda would be able to help out?

**Comment by CoralineAda** [comment]
I'd be happy to review.

**Comment by toch** [comment]
@juliancheal just published the coc cf http://fosdem.rubybelgium.be/coc there is also a statement on the cfp page http://fosdem.rubybelgium.be/cfp

@CoralineAda it would be great, thanks a lot for your help. could you have a look at http://fosdem.rubybelgium.be/coc and https://github.com/brug-be/code_of_conduct/blob/master/README.md please?

**Comment by CoralineAda** [comment]
I think this looks great. Congrats on taking the first steps toward a welcoming and inclusive environment!

**Comment by toch** [comment]
Thanks a lot for the review @CoralineAda

**Comment by toch** [comment]
except if there is still something to update or improve on that topic I close it for now.
