### ISSUE TITLE
Dinner

### ISSUE THREAD

**Issue by toch** [fosdem-ruby/fosdem-ruby.github.io#4]
Find a nice place for an open dinner with the speakers.

**Comment by YorickPeterse** [comment]
Same here, fine with anything. If worst comes to worst we can always order something, although it's not that romantic :)

**Comment by toch** [comment]
@rtyler I've contacted Houtsiplou and Boston Steak House.

There are not close (but it's relative as Brussels is small), but they cook very good burgers (and have vegie/vegan options), they are the only option to welcome a 20+ Group, and they are close to good bars (especially Houtsiplou).

Last year fosdem Ruby burger gathered 25+ attendants, so we can expect more. Do we limit at 30, or do we try to go to 50?

**Comment by toch** [comment]
@fosdem-ruby/owners Ok got the answer.

For Boston, we can book a table for 15 during the weekend. Another option is to book the "club", a private part of the restaurant for 25. There is a booking fee of 150€
For Houtsiplou, we can book a table for 15 during the weekend :/. I ask an offer for more. The boss will call me back.

One hack consists in booking multiple big tables at different name.

**Comment by toch** [comment]
I've contacted another good option is Mirabelle. It's very close to the FOSDEM, not burger, they can host big group (45) to very big group (until 80). I think this is a good brasserie.

Houtsiplou answered me ok for 20. I asked if possible if we pay an additional fee.
