### ISSUE TITLE
Karaoke

### ISSUE THREAD

**Issue by zzak** [fosdem-ruby/fosdem-ruby.github.io#9]
We have a tradition, it's called #rubykaraoke and we're starting to think about it for Fosdem:
https://twitter.com/amateurhuman/status/557266396275421184

I wanted to move the discussion her to figure out how to make it happen. Probably need to find a good place that does karaoke as the first thing.

/cc @hone @amateurhuman @headius @plexus @estolfo

**Comment by headius** [comment]
FWIW, I will be in town Thursday mid-day and leaving Sunday mid-day. FOSDEM
party is Friday, Ruby Burger is Saturday...so either karaoke needs to be
after dinner on Saturday or sometime Thursday evening (and there's a chance
I won't make it on Thursday due to jetlag and travel tiredness).

**Comment by rtyler** [comment]
Karaoke isn't quite my thing, you guys are on your own :P
